### ISSUE TITLE
Explain the difference between the official directive and this one

### ISSUE THREAD

**Issue by LifeIsStrange** [byteboomers/vue-autofocus-directive#16]
https://vuejs.org/v2/guide/custom-directive.html
The documentation show a simple directive, and the first commit of this repo matched it.
However the directive in this repo got more complex, what are the added value(s) of this directive over the documented one?
https://github.com/byteboomers/vue-autofocus-directive/blob/master/src/vue-autofocus-directive.js
(performance? correctness?) as I do not understand the changes

**Comment by botre** [comment]
Hello,

This directive additionally supports using a dynamic value to trigger the focus.

![image](https://user-images.githubusercontent.com/10811687/135424728-f104063b-7328-4e4b-805d-6ddf8ab4cc4c.png)

That's pretty much it.

**Comment by LifeIsStrange** [comment]
Thank you
